### ISSUE TITLE
red name

### ISSUE THREAD

**Issue by to-dr** [revilheart/rhSGST#15]
not sure if bug, but before red username was for rule violations I guess, now I have some names in red, but no violations there, like in prtscrn below

![prtscrn](http://i.imgur.com/pqVOCWX.png)

**Comment by revilheart** [comment]
Do you have the latest version? This was happening a while ago but I fixed it. Could it be a conflict with another script?

**Comment by to-dr** [comment]
might be something with cashe, as above user is now green after rechecking. and as my net is and will be shit for next 2 weeks at least, took me a while to find another case like this, and same, red name and 0/0. after rechecking green. I guess if I would clear cashe should be fine, but weird to happen anyway

**Comment by to-dr** [comment]
and  now it got more complicated - on /user/* everyone are either green or red (and if not checked they appear as green) - restarted browser, turned off other scripts and stylish.

**Comment by to-dr** [comment]
and now is all good again...must be something on my side, sorry

**Comment by revilheart** [comment]
On "/user/" that's SG native, because on that page the colors green / red represent who marked the games as received or not. My colors are a bit stronger on that page, so you can differentiate them.

And yes, re-checking "fixes" it, but I thought I added a permanent fix to it a while back. You didn't answer my question about if you're using the latest version.

**Comment by to-dr** [comment]
every day I see 'rhSGT succesfully updated'' lol while I was checking just now I saw 4.11, and then saw pop up again, refresh and 4.14 :) 
I thought below was normal ![](http://i.imgur.com/niHM5GK.png)

**Comment by revilheart** [comment]
Ah looks like that theme you're using alters the normal colors. Well if it's fixed now then great. :)

**Comment by to-dr** [comment]
I guess :) with other scripts/stylish disabled, yeah, your green is little bit bolder lol :D 
thanks for all the new features! 
not sure if possible - date of adding to BL/WL?
aaaaaaand personal stats charts are bit umm lying (not excalty lol) - the do not show drop in BL/WL :)
possible to /correct/ them? :p

**Comment by revilheart** [comment]
SG already shows date of adding to whitelist / blacklist, and nope, it's not possible to correct the charts.

**Comment by ldeman** [comment]
i think they mean to have your highlight show the date of add.
![image](https://cloud.githubusercontent.com/assets/10275898/23462553/ecc88b0c-fe53-11e6-9298-452ce56d3ad9.png)

basically something like - make that popup text say:
You've had Revilheart whitelisted since: 11/10/2016, 7:50:28 PM - 3 months ago

**Comment by to-dr** [comment]
yes and no :) yes, d3m4ns idea is nice/convenient
no - I did not know(tice) the date is already in the list lol :D

**Comment by revilheart** [comment]
Well, if there isn't a bug anymore, I'm closing this. Feel free to submit d3m4n's idea as a new issue if you want it.
