### ISSUE TITLE
[Enhancement] Replace the term Cache with Database

### ISSUE THREAD

**Issue by gizellos** [revilheart/rhSGST#30]
Hi, you use the term cache and it is IMO kinda confusing.  Shouldn't you use the word database instead? IMHO database would be much more understable for normal users. Cache is term mainly for programmers.

**Comment by ldeman** [comment]
if he uses the word database people might think it's a lot more permanent then it really is, since it would all get wiped away with a browser cache wipe.

"why did my database get wiped because i cleared cache?"  xD

**Comment by gizellos** [comment]
But the data you get from the checkers are quite permanent. At least, they should be. So users should  theoretically decide just about the permanent data in the database. Only script should care about caches.

**Comment by ldeman** [comment]
there is no database besides what's contained inside your cache.  it's not permanent at all.  that was actually my first argument about how it was labeled "permanent notes" when it wasn't really permanent at all.

**Comment by gizellos** [comment]
I see, it's a pity it is not really permanent, I didn't realize that. :(

It would be good if it saved to dropbox or to a similar place. Some apps use a folder Apps in the root folder and it is cool.

**Comment by ldeman** [comment]
yeah i frequently export all the info and toss the json into my dropbox, as well as tampermonkeys export can include data when/if you backup all scripts.  so there's kinda both types of backups i do regularly.

though i agree, a direct export to dropbox / google drive would be nice.. but probably a pain to integrate.

**Comment by revilheart** [comment]
I think cache is the correct term, because it relates to something that is updated after a certain period, and the checker results are updated after 24 hours if you try to check those users again.

As to implementing a Dropbox export, I'll look into it, but like d3m4n said, you can overcome that by exporting your data every once in a while until / if I implement a direct export.

**Comment by gizellos** [comment]
The problem is that if someone hears the word cache, they think that they can safely delete it  because they don't lose their data (because they suppose it is just some data for the script to work faster). But in this case, if you delete the cache, you lost all the data. So if you call it database, people who don't want to delete the date won't clear it, however when this is called cache, some people who don't want to lose the data may lose them, because they will delete it.

About the dropbox, I meant more something like automatic synchronisation than just an export. Is it even possible? I know that android apps can do it, but I am not sure about web applications such as user scripts.

**Comment by revilheart** [comment]
There isn't a way to delete the cache though, unless you delete the users data through the settings menu. Clearing the cache only replaces it. I might even remove the option to clear the cache, since it was only there to solve issues that people were having with the results by resetting them. Removing that option would also help identify those issues better and actually fix them.

I don't know if it's possible, I'll learn more about it.

**Comment by gizellos** [comment]
Yes, that would be a solution too. :)

**Comment by ldeman** [comment]
>  I might even remove the option to clear the cache

i hope you only mean for the wl/bl & sgtools checkers menus and not the data management settings menu.  ^^

**Comment by revilheart** [comment]
Yeah, I meant outside of the settings menu. But when I add the option to delete checker data separately from the user data, I'll remove it from the settings menu as well.

**Comment by revilheart** [comment]
Hope it's better now with the removal of that option.

**Comment by gizellos** [comment]
You bet! Thanks.
